version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: curi-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - PORT=5000
      # Permitir conexiones desde cualquier host
      - HOST=0.0.0.0
    networks:
      - curi-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: curi-frontend
    restart: unless-stopped
    ports:
      - "3006:3006"
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=production
      # Esta variable sólo es importante durante la construcción, en ejecución usará la lógica de config.ts
      - NEXT_PUBLIC_API_URL=
      - PORT=3006
      # Permitir conexiones desde cualquier host
      - HOST=0.0.0.0
    depends_on:
      - backend
    networks:
      - curi-network

networks:
  curi-network:
    driver: bridge