version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: curi-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - PORT=3001
    networks:
      - curi-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: curi-frontend
    restart: unless-stopped
    ports:
      - "3006:3006"
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:3001/api
      - PORT=3006
    depends_on:
      - backend
    networks:
      - curi-network

networks:
  curi-network:
    driver: bridge